instanceName: dboxed-example

db:
  url: postgresql://${POSTGRES_DBOXED_USER}:${POSTGRES_DBOXED_PASSWORD}@postgres:5432/${POSTGRES_DBOXED_DATABASE}
  migrate: true

auth:
  oidc:
    issuerUrl: "https://${DBOXED_HOSTNAME}/dex"
    clientId: "dboxed"

    adminUsers:
      - username: "${ADMIN_EMAIL}"

server:
  listenAddress: "0.0.0.0:5000"
  baseUrl: "https://${DBOXED_HOSTNAME}"

defaultWorkspaceQuotas:
  maxLogBytes: 100Mi
